using UnityEngine;

public class MoveDownByScore : MonoBehaviour
{
    private int lastScore = 0;

    [Header("İ’è€–Ú")]
    public float moveAmountPerScore = 0.0000001f; // š ¬‚³‚ß‚É‰Šúİ’èi0.01‚È‚Çj

    void Update()
    {
        int currentScore = TouchLine.Score;

        if (currentScore > lastScore)
        {
            int scoreDifference = currentScore - lastScore;

            // ˆÚ“®—Ê‚ğŒ¸‚ç‚µ‚ÄA‚ä‚Á‚­‚è‰º‚ª‚é
            Vector3 pos = transform.position;
            pos.y -= moveAmountPerScore * scoreDifference;
            transform.position = pos;

            lastScore = currentScore;
        }
    }
}